name: Build and Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          5.0.x
    - name: Install dependencies
      run: dotnet restore src/GeoJSON.Net.sln
    - name: Build
      run: dotnet build src/GeoJSON.Net.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/GeoJSON.Net.sln --no-restore --verbosity normal
